name: C++

on:

  push: 
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3

      
      - name: Set up compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake make cppcheck clang-tidy

      
      - name: Lint code
        run: |
          clang-tidy Lab1.cpp --checks=* -- -std=c++11

      
      - name: Build project
        run: |
          g++ -o my_program Lab1.cpp
      
      - name: Run tests
        run: |
          ./my_program