name: C++

on:
  push: 
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up compiler and Google Test
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake make cppcheck clang-tidy libgtest-dev
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp *.a /usr/lib

      - name: Lint code
        run: |
          clang-tidy Lab1.cpp --checks=* -- -std=c++11
          clang-tidy Test.cpp --checks=-google-* -- -std=c++11

      - name: Build project
        run: |
          g++ -std=c++11 -o my_program Lab1.cpp Test.cpp -lgtest -lgtest_main -pthread

      - name: Run tests
        run: |
          ./my_program
